### ISSUE TITLE
PowerVu: problem selecting the correct s-box for each ecm 

### ISSUE THREAD

**Issue by Purrfect4711** [oscam-emu/oscam-emu#172]
Hi!

"For EMM decryption the sbox set can be chosen during the personalisation of the ISE and can't be changed during the runtime.
For ECM decryption the sbox set can be chosen by a bit in the ECM. The same byte in nano 20 that selects the even/odd key can control with a set bit 3 (mask 0x08) that the alternate sboxes are used." In a forum I also found "first try with sbox mode = 0 (primary tables), if it works, great, otherwise test the 0xA0 mode (secondary tables)."

Unfortunately oscam-emu doesn't support this, yet. Is it possible to add this feature?

Thanks and regards,
Purrfect

**Comment by jahntheman** [comment]
Thank you. 
Has been fixed.

**Comment by budiarno** [comment]
Hi, it seems this problem still persist. 

First screenshot is the working one on OSCam-Emu:
![nss 12 change - sbox 00](https://cloud.githubusercontent.com/assets/15664372/12194256/1acffce6-b621-11e5-8c82-94462c982677.jpg)

Now, the channel has changed:
![nss 12 change - sbox a0](https://cloud.githubusercontent.com/assets/15664372/12194274/4f9d2e44-b621-11e5-9dea-2cc176a07cfc.jpg)

We only get blank picture on these channels (for example on TCM at Asiasat7 and Astro on Measat 3). Wish there a solution for this problem.
